Traceback (most recent call last):
  File "C:\Users\npgreenfield\AppData\Local\Temp\ipykernel_4752\510410227.py", line 7, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "C:\Users\npgreenfield\AppData\Local\Temp\ipykernel_4752\2516175900.py", line 7, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
